version: '3.7'
services:
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./app:/usr/share/nginx/html
  web2:
    image: nginx:latest
    ports:
      - "8989:80"
    volumes:
      - ./app2:/usr/share/nginx/html